# roles/personal/tasks/main.yml
---

- name: Install packages
  pacman:
    name: "{{ item }}"
    state: present
  with_items: personal_packages
  tags: personal

- name: Ensure service is started
  service:
    name: "{{ personal_service }}"
    state: started
    enabled: true
  tags: personal
